In [2]:
import pandas as pd 
import numpy as np
from matplotlib.pyplot import imshow, show, colorbar
import matplotlib.pyplot as plt

In [54]:
#Training Set
X = np.load('E:/jupyter notebook/bacteria-ID-master/data/X_reference.npy')
y = np.load('E:/jupyter notebook/bacteria-ID-master/data/y_reference.npy')
Gram_class=[]
Gram_idx=[]
is_Gram=[]
X_train=[]
y_train=[]
for i in range(len(y)-1):
    if y[i]==14 or y[i]==15 or y[i]==18:
        y[i]=1
        Gram_class.append(y[i])
        Gram_idx.append(i)
    elif y[i]==16 or y[i]==17:
        y[i]=0
        Gram_class.append(y[i])
        Gram_idx.append(i)
for idx in Gram_idx:
    is_Gram.append(X[idx])
np.savetxt('E:/jupyter notebook/bacteria-ID-master/data/is_Gram.txt',is_Gram)
X_train = np.loadtxt('E:/jupyter notebook/bacteria-ID-master/data/is_Gram.txt')
y_train=Gram_class
print(X_train)

[[0.30461474 0.40388757 0.27940847 ... 0.22139561 0.21940288 0.01476507]
 [0.42232555 0.21010819 0.41121444 ... 0.21202893 0.2231522  0.32553489]
 [0.38681646 0.42464102 0.52197753 ... 0.34478089 0.43193215 0.31830965]
 ...
 [0.13588075 0.13319926 0.07925391 ... 0.24329824 0.08236129 0.13830593]
 [0.04071882 0.05853344 0.09414933 ... 0.17647713 0.11225325 0.12813397]
 [0.10548363 0.08262433 0.16251541 ... 0.15013701 0.11030621 0.15610015]]


In [3]:
X = np.load('E:/jupyter notebook/bacteria-ID-master/data/X_reference.npy')
y = np.load('E:/jupyter notebook/bacteria-ID-master/data/y_reference.npy')
mask_1 = (y == 14) | (y == 15) | (y == 18)
mask_2 = (y == 16) | (y == 17) 
idx = np.where(mask_1 | mask_2)
X_train = []
for i in idx:
    X_train.append(X[idx])
X_train = np.array(X_train)
X_train = X_train.reshape(X_train.shape[0]*X_train.shape[1], X_train.shape[2])

np.savetxt('E:/jupyter notebook/bacteria-ID-master/data/X_train.txt',X_train)
X_train_1 = np.loadtxt('E:/jupyter notebook/bacteria-ID-master/data/X_train.txt')

y[mask_1] = 1
y[mask_2] = 0
y_train = y[mask_1]
y_train = y[mask_2]


FileNotFoundError: [Errno 2] No such file or directory: 'X_reference.npy'